version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data sources
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales of greenweez / we have one per product_id found in each order_id
        columns:
          - name: orders_id
            description: Order ID part of the primary key
            tests:
              - not_null
          - name: pdt_id
            description: Product ID part of the primary key
            tests:
              - not_null

      - name: product
        identifier: raw_gz_product
        description: Purchase price by product_id
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: Ship cost and log cost by order_id
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

      # Updated source names for ad campaigns
      - name: adwords google
        identifier: raw_gz_adwords
        description: Google Ads campaign data

      - name: bing microsoft
        identifier: raw_gz_bing
        description: Microsoft Bing Ads campaign data

      - name: criteo ads
        identifier: raw_gz_criteo
        description: Criteo Ads campaign data

      - name: facebook ads
        identifier: raw_gz_facebook
        description: Facebook Ads campaign data

models:
  - name: stg_adwords_google
    description: Staging model for Google Ads data.
    columns:
      - name: date_date
        description: The date of the ad campaign.
      - name: paid_source
        description: The source of the paid ad (e.g., Google Ads).
      - name: campaign_key
        description: Unique key for the campaign.
      - name: campaign_name
        description: The name of the ad campaign.
      - name: ads_cost
        description: The cost of the ad campaign.
      - name: impression
        description: Number of times the ad was displayed.
      - name: click
        description: Number of clicks received.

  - name: stg_bing_microsoft
    description: Staging model for Microsoft Bing Ads data.
    columns:
      - name: date_date
        description: The date of the ad campaign.
      - name: paid_source
        description: The source of the paid ad (e.g., Bing Ads).
      - name: campaign_key
        description: Unique key for the campaign.
      - name: campaign_name
        description: The name of the ad campaign.
      - name: ads_cost
        description: The cost of the ad campaign.
      - name: impression
        description: Number of times the ad was displayed.
      - name: click
        description: Number of clicks received.

  - name: stg_criteo_ads
    description: Staging model for Criteo Ads data.
    columns:
      - name: date_date
        description: The date of the ad campaign.
      - name: paid_source
        description: The source of the paid ad (e.g., Criteo Ads).
      - name: campaign_key
        description: Unique key for the campaign.
      - name: campaign_name
        description: The name of the ad campaign.
      - name: ads_cost
        description: The cost of the ad campaign.
      - name: impression
        description: Number of times the ad was displayed.
      - name: click
        description: Number of clicks received.

  - name: stg_facebook_ads
    description: Staging model for Facebook Ads data.
    columns:
      - name: date_date
        description: The date of the ad campaign.
      - name: paid_source
        description: The source of the paid ad (e.g., Facebook Ads).
      - name: campaign_key
        description: Unique key for the campaign.
      - name: campaign_name
        description: The name of the ad campaign.
      - name: ads_cost
        description: The cost of the ad campaign.
      - name: impression
        description: Number of times the ad was displayed.
      - name: click
        description: Number of clicks received.
